#!/usr/bin/env python

import sys
import os.path
import getopt

import shiftertools
from shiftertools.decoutils import *

CMD = "sh"
QUEUE="short"
REPROC=False
APATH=shiftertools.RECODATABASEPATH
SPLITTRG=True

def shelp():

    print("\nUsage: runFileDeco [-s] [-t] [-q queue] [-p path] [-r] RUN_NUMBER FILE")
    print()      
    print( "    Decode binary data file FILE from run RUN_NUMBER")
    print()
    print( "    Options: ")
    print( "      * -s, --qsub: send job the the batch system [default: %s]"%CMD)
    print( "      * -q, --queue: queue to submit job [default: %s"%QUEUE)
    print( "      * -r, --reprocess: reprocess file if already exists [default: %s]"%REPROC)
    print( "      * -p, --path: root path for output files [default: %s]"%APATH)
    print( "      * -t, --split: split trigger1 and trigger2 data [default: %s]"%SPLITTRG)
    print()

if __name__ == "__main__":
    
    try: opts,args=getopt.getopt(sys.argv[1:],'hsq:rp:t',
                                 ["help","sub","queue=","reprocess","path=",'split'])
    except getopt.GetoptError as err: error(str(err),shelp)
    
    try: RUN,FILE = int(args[0]),int(args[1])
    except IndexError:  error("Wrong arguments!",shelp)

    for o,v in opts: 
        
        if o in ('-h','--help'):
            shelp()
            sys.exit()
        elif o in ('-s','--sub'): CMD = "qsub"
        elif o in ('-q','--queue'): QUEUE=v
        elif o in ('-r','--reprocess'): REPROC=True
        elif o in ('-p','--path'): APATH=v
        elif o in ('-t','--split'): SPLITTRG=False
            
    shiftertools.setRawDataPaths()
    shiftertools.setRecoedDataPaths(APATH)
    
    decodeFile(RUN,FILE,QUEUE,CMD,REPROC,SPLITTRG)

  
